chore(build):[#222] add message if secrets not defined

diff --git a/.github/workflows/integration-test-DEV.yaml b/.github/workflows/integration-test-DEV.yaml
--- a/.github/workflows/integration-test-DEV.yaml
+++ b/.github/workflows/integration-test-DEV.yaml
@@ -19,8 +19,37 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
+
+
+
 jobs:
+
+  check-config:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if DEV_REGULAR_USER_API_KEY is defined
+        run: |
+          if [[ -z "${{ secrets.DEV_REGULAR_USER_API_KEY }}" ]]; then
+            echo "Error: Missing secret: Please configure DEV_REGULAR_USER_API_KEY."
+            exit 1
+          fi
+      - name: Check if DEV_ADMIN_USER_API_KEY is defined
+        run: |
+          if [[ -z "${{ secrets.DEV_ADMIN_USER_API_KEY }}" ]]; then
+            echo "Error: Missing secret: Please configure DEV_ADMIN_USER_API_KEY."
+            exit 1
+          fi
+  # TODO it this really required?
+  #      - name: Check if IRS_CUCUMBER_PUBLISH_TOKEN is defined
+  #        run: |
+  #          if [[ -z "${{ secrets.IRS_CUCUMBER_PUBLISH_TOKEN }}" ]]; then
+  #            echo "Error: Missing secret: Please configure IRS_CUCUMBER_PUBLISH_TOKEN."
+  #            exit 1
+  #          fi
+  #        shell: bash
+
   trigger-integration-test:
+    needs: check-config
     uses: ./.github/workflows/cucumber-integration-test.yaml
     secrets:
       regularUserApiKey: ${{ secrets.DEV_REGULAR_USER_API_KEY }}
