chore(build):[#222] try to make publish optional

diff --git a/.github/workflows/integration-test-DEV.yaml b/.github/workflows/integration-test-DEV.yaml
--- a/.github/workflows/integration-test-DEV.yaml
+++ b/.github/workflows/integration-test-DEV.yaml
@@ -44,13 +44,13 @@ jobs:
             echo "Error: Missing secret: Please configure DEV_ADMIN_USER_API_KEY."
             exit 1
           fi
-      - name: Check if IRS_CUCUMBER_PUBLISH_TOKEN is defined
-        run: |
-          if [[ -z "${{ secrets.IRS_CUCUMBER_PUBLISH_TOKEN }}" ]]; then
-            echo "Error: Missing secret: Please configure IRS_CUCUMBER_PUBLISH_TOKEN."
-            exit 1
-          fi
-        shell: bash
+#      - name: Check if IRS_CUCUMBER_PUBLISH_TOKEN is defined
+#        run: |
+#          if [[ -z "${{ secrets.IRS_CUCUMBER_PUBLISH_TOKEN }}" ]]; then
+#            echo "Error: Missing secret: Please configure IRS_CUCUMBER_PUBLISH_TOKEN."
+#            exit 1
+#          fi
+#        shell: bash
 
   trigger-integration-test:
     needs: check-config
